version: "2"

services:
  frontend:
    build: ./finup-frontend
    ports:
      - "8081:8081"
    links:
      - backend:backend
      - log:log
  backend:
    build: ./finup-backend
    ports: 
      - "8080:8080"
    links:
      - db:db
      - broker:broker
      - log:log
    environment:
      - geochallenge.survey.url=http://${DOCKER_MACHINE_IP}:8081/survey.html?key=%s
  db:
   image: mongo:latest
   ports:
      - "27017:27017"
  broker:
   image: rabbitmq:3.6.5-management
   ports:
      - "5672:5672"
      - "15672:15672"
  log:
   image: pblittle/docker-logstash
   ports:
      - "9292:9292"
      - "9200:9200"
      - "9998:9998"
      - "9999:9999/udp"
   volumes:
      - ./log/logstash-embedded.conf:/opt/logstash/conf.d/logstash-embedded.conf
